---

- name: install apache2 on rasppi3 ans raspi4 
  hosts: all
  gather_facts: true
  become: true
  #vars:
    # apache_package: apache2
    # php_package: libapache2-mod-php

  tasks:
  - name: install apache and php  package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

