---

- name: install apache2 on rasppi3 ans raspi4 
  hosts: raspi3
  gather_facts: true
  become: true
  #gather_facts: no
  tags: always
  #vars:
  #  apache_package: apache2
  #  php_package: libapache2-mod-php

  tasks:
  - name: install apache and php  package
    tags: apache, package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name : print version and device name
    tags:
    - print
    - debug
    - device_info
    debug:
      msg: "{{ansible_user}}: the device name is {{ device_name}} with the version {{ version }}"

  
    